PATH %PATH%;S:\SYSTEM\BP\BIN
BPC /B /E..\ BURN.PAS 
BPC /B /E..\ 2001.PAS 
BPC /B /E..\ DIABLO.PAS 
BPC /B /E..\ DISPLAY.PAS 
BPC /B /E..\ DRAGON.PAS 
BPC /B /E..\ FIRE2.PAS 
BPC /B /E..\ FLAMES.PAS 
BPC /B /E..\ FLAMES2.PAS 
BPC /B /E..\ FLAMTEXT.PAS 
BPC /B /E..\ FLAMTXT2.PAS 
BPC /B /E..\ FLASH1.PAS 
BPC /B /E..\ FLASH2.PAS 
BPC /B /E..\ FRACT.PAS 
BPC /B /E..\ ROMAN.PAS 
BPC /B /E..\ SOFT.PAS 
BPC /B /E..\ SQR1.PAS 
BPC /B /E..\ SQR2.PAS 
BPC /B /E..\ SSAVER.PAS 
BPC /B /E..\ WINDOWS.PAS 
BPC /B /E..\ WORMS.PAS 



